//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhooshDI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WhooshDI.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ArgumentExceptionNotAReferenceType {
            get {
                return ResourceManager.GetString("ArgumentExceptionNotAReferenceType", resourceCulture);
            }
        }
        
        public static string ArgumentExceptionTypeIsNotAssignable {
            get {
                return ResourceManager.GetString("ArgumentExceptionTypeIsNotAssignable", resourceCulture);
            }
        }
        
        public static string CircularDependencyExceptionIsDetected {
            get {
                return ResourceManager.GetString("CircularDependencyExceptionIsDetected", resourceCulture);
            }
        }
        
        public static string DuplicateElementExceptionDuplicateImplementation {
            get {
                return ResourceManager.GetString("DuplicateElementExceptionDuplicateImplementation", resourceCulture);
            }
        }
        
        public static string DuplicateElementExceptionDuplicateImplementationName {
            get {
                return ResourceManager.GetString("DuplicateElementExceptionDuplicateImplementationName", resourceCulture);
            }
        }
        
        public static string InvalidOperationExceptionAmbiguityInDependencyResolution {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionAmbiguityInDependencyResolution", resourceCulture);
            }
        }
        
        public static string InvalidOperationExceptionCantInstantiateType {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionCantInstantiateType", resourceCulture);
            }
        }
        
        public static string InvalidOperationExceptionDependencyNotConfigured {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionDependencyNotConfigured", resourceCulture);
            }
        }
        
        public static string InvalidOperationExceptionNoConfiguration {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionNoConfiguration", resourceCulture);
            }
        }
        
        public static string InvalidOperationExceptionNoImplementationWithSuchName {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionNoImplementationWithSuchName", resourceCulture);
            }
        }
        
        public static string InvalidOperationExceptionPropertySetterNotAccessible {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionPropertySetterNotAccessible", resourceCulture);
            }
        }
    }
}
